import streamlit as st

st.set_page_config(page_title="AI Recommendations", layout="wide")
st.title("AI Cost-Optimization Recommendations")

st.markdown(
    "Prioritized actionable recommendations generated by cross-referencing ML spend anomalies with contract notice windows:"
)

st.error("CRITICAL: Review Zoom Subscription Prior to 30-Day Cancellation Window")
st.write("**Est. Annual Savings:** $18,000")
st.write(
    "**Analysis:** Auto-renewal notice window closes in 12 days. Restrictive lock-in clause detected."
)
st.button("Draft Cancellation Notice", key="btn_zoom")

st.divider()

st.warning("HIGH: Consolidate Duplicate Slack Licenses Across Departments")
st.write("**Est. Annual Savings:** $12,000")
st.write(
    "**Analysis:** Independent active subscriptions detected across Engineering and Marketing. Consolidate into single enterprise agreement."
)
st.button("Initiate Consolidation Review", key="btn_slack")