"""Initial baseline migration

Revision ID: c1ed2245f337
Revises: 
Create Date: 2026-08-03 12:28:49.846264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1ed2245f337'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('vendor_name', sa.String(), nullable=True),
    sa.Column('contract_value', sa.Float(), nullable=True),
    sa.Column('notice_period_days', sa.Integer(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_analysis_filename'), 'contract_analysis', ['filename'], unique=False)
    op.create_index(op.f('ix_contract_analysis_id'), 'contract_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_contract_analysis_risk_level'), 'contract_analysis', ['risk_level'], unique=False)
    op.create_index(op.f('ix_contract_analysis_vendor_name'), 'contract_analysis', ['vendor_name'], unique=False)
    op.drop_index(op.f('ix_contract_metadata_id'), table_name='contract_metadata')
    op.drop_table('contract_metadata')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_vendor_name'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('vendor_name', sa.VARCHAR(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('department_id', sa.VARCHAR(), nullable=False),
    sa.Column('card_last_four', sa.VARCHAR(length=4), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_vendor_name'), 'transactions', ['vendor_name'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=1)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_table('contract_metadata',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(), nullable=False),
    sa.Column('file_path', sa.VARCHAR(), nullable=False),
    sa.Column('file_size_bytes', sa.INTEGER(), nullable=False),
    sa.Column('upload_timestamp', sa.DATETIME(), nullable=True),
    sa.Column('processed_status', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_metadata_id'), 'contract_metadata', ['id'], unique=False)
    op.drop_index(op.f('ix_contract_analysis_vendor_name'), table_name='contract_analysis')
    op.drop_index(op.f('ix_contract_analysis_risk_level'), table_name='contract_analysis')
    op.drop_index(op.f('ix_contract_analysis_id'), table_name='contract_analysis')
    op.drop_index(op.f('ix_contract_analysis_filename'), table_name='contract_analysis')
    op.drop_table('contract_analysis')
    # ### end Alembic commands ###
